
sonar.projectKey=process.env.SONAR_TOKEN
sonar.organization=process.env.SONAR_ORGANIZATION
sonar.sources=src
sonar.exclusions=node_modules/**,.nitro/**,.output/**,dist/**
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.sourceEncoding=UTF-8