/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationsNewRouteImport } from './routes/_app/organizations/new'
import { Route as AppOrganizationsSlugRouteRouteImport } from './routes/_app/organizations/$slug/route'
import { Route as AppOrganizationsSlugSettingsRouteImport } from './routes/_app/organizations/$slug/settings'
import { Route as AppOrganizationsSlugRolesRouteImport } from './routes/_app/organizations/$slug/roles'
import { Route as AppOrganizationsSlugMembersRouteImport } from './routes/_app/organizations/$slug/members'
import { Route as AppOrganizationsSlugDetectionRouteImport } from './routes/_app/organizations/$slug/detection'
import { Route as AppOrganizationsSlugDashboardRouteImport } from './routes/_app/organizations/$slug/dashboard'
import { Route as AppOrganizationsSlugProjectsIndexRouteImport } from './routes/_app/organizations/$slug/projects/index'
import { Route as AppOrganizationsSlugProjectsProjectIdRouteImport } from './routes/_app/organizations/$slug/projects/$projectId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsNewRoute = AppOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationsSlugRouteRoute =
  AppOrganizationsSlugRouteRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationsSlugSettingsRoute =
  AppOrganizationsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugRolesRoute =
  AppOrganizationsSlugRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugMembersRoute =
  AppOrganizationsSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugDetectionRoute =
  AppOrganizationsSlugDetectionRouteImport.update({
    id: '/detection',
    path: '/detection',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugDashboardRoute =
  AppOrganizationsSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugProjectsIndexRoute =
  AppOrganizationsSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)
const AppOrganizationsSlugProjectsProjectIdRoute =
  AppOrganizationsSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppOrganizationsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/api-reference': typeof ApiReferenceRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/api/test': typeof ApiTestRoute
  '/organizations/$slug': typeof AppOrganizationsSlugRouteRouteWithChildren
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/organizations/$slug/dashboard': typeof AppOrganizationsSlugDashboardRoute
  '/organizations/$slug/detection': typeof AppOrganizationsSlugDetectionRoute
  '/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/organizations/$slug/roles': typeof AppOrganizationsSlugRolesRoute
  '/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/organizations/$slug/projects/$projectId': typeof AppOrganizationsSlugProjectsProjectIdRoute
  '/organizations/$slug/projects/': typeof AppOrganizationsSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/api-reference': typeof ApiReferenceRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/api/test': typeof ApiTestRoute
  '/organizations/$slug': typeof AppOrganizationsSlugRouteRouteWithChildren
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/organizations/$slug/dashboard': typeof AppOrganizationsSlugDashboardRoute
  '/organizations/$slug/detection': typeof AppOrganizationsSlugDetectionRoute
  '/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/organizations/$slug/roles': typeof AppOrganizationsSlugRolesRoute
  '/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/organizations/$slug/projects/$projectId': typeof AppOrganizationsSlugProjectsProjectIdRoute
  '/organizations/$slug/projects': typeof AppOrganizationsSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/api-reference': typeof ApiReferenceRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/test': typeof ApiTestRoute
  '/_app/organizations/$slug': typeof AppOrganizationsSlugRouteRouteWithChildren
  '/_app/organizations/new': typeof AppOrganizationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/organizations/$slug/dashboard': typeof AppOrganizationsSlugDashboardRoute
  '/_app/organizations/$slug/detection': typeof AppOrganizationsSlugDetectionRoute
  '/_app/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/_app/organizations/$slug/roles': typeof AppOrganizationsSlugRolesRoute
  '/_app/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/_app/organizations/$slug/projects/$projectId': typeof AppOrganizationsSlugProjectsProjectIdRoute
  '/_app/organizations/$slug/projects/': typeof AppOrganizationsSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/api-reference'
    | '/logout'
    | '/onboarding'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/test'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/api/auth/$'
    | '/organizations/'
    | '/organizations/$slug/dashboard'
    | '/organizations/$slug/detection'
    | '/organizations/$slug/members'
    | '/organizations/$slug/roles'
    | '/organizations/$slug/settings'
    | '/organizations/$slug/projects/$projectId'
    | '/organizations/$slug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/api-reference'
    | '/logout'
    | '/onboarding'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/test'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/api/auth/$'
    | '/organizations'
    | '/organizations/$slug/dashboard'
    | '/organizations/$slug/detection'
    | '/organizations/$slug/members'
    | '/organizations/$slug/roles'
    | '/organizations/$slug/settings'
    | '/organizations/$slug/projects/$projectId'
    | '/organizations/$slug/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/accept-invite'
    | '/api-reference'
    | '/logout'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/api/test'
    | '/_app/organizations/$slug'
    | '/_app/organizations/new'
    | '/api/auth/$'
    | '/_app/organizations/'
    | '/_app/organizations/$slug/dashboard'
    | '/_app/organizations/$slug/detection'
    | '/_app/organizations/$slug/members'
    | '/_app/organizations/$slug/roles'
    | '/_app/organizations/$slug/settings'
    | '/_app/organizations/$slug/projects/$projectId'
    | '/_app/organizations/$slug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organizations/new': {
      id: '/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AppOrganizationsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organizations/$slug': {
      id: '/_app/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof AppOrganizationsSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organizations/$slug/settings': {
      id: '/_app/organizations/$slug/settings'
      path: '/settings'
      fullPath: '/organizations/$slug/settings'
      preLoaderRoute: typeof AppOrganizationsSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/roles': {
      id: '/_app/organizations/$slug/roles'
      path: '/roles'
      fullPath: '/organizations/$slug/roles'
      preLoaderRoute: typeof AppOrganizationsSlugRolesRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/members': {
      id: '/_app/organizations/$slug/members'
      path: '/members'
      fullPath: '/organizations/$slug/members'
      preLoaderRoute: typeof AppOrganizationsSlugMembersRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/detection': {
      id: '/_app/organizations/$slug/detection'
      path: '/detection'
      fullPath: '/organizations/$slug/detection'
      preLoaderRoute: typeof AppOrganizationsSlugDetectionRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/dashboard': {
      id: '/_app/organizations/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/organizations/$slug/dashboard'
      preLoaderRoute: typeof AppOrganizationsSlugDashboardRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/projects/': {
      id: '/_app/organizations/$slug/projects/'
      path: '/projects'
      fullPath: '/organizations/$slug/projects/'
      preLoaderRoute: typeof AppOrganizationsSlugProjectsIndexRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
    '/_app/organizations/$slug/projects/$projectId': {
      id: '/_app/organizations/$slug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/organizations/$slug/projects/$projectId'
      preLoaderRoute: typeof AppOrganizationsSlugProjectsProjectIdRouteImport
      parentRoute: typeof AppOrganizationsSlugRouteRoute
    }
  }
}

interface AppOrganizationsSlugRouteRouteChildren {
  AppOrganizationsSlugDashboardRoute: typeof AppOrganizationsSlugDashboardRoute
  AppOrganizationsSlugDetectionRoute: typeof AppOrganizationsSlugDetectionRoute
  AppOrganizationsSlugMembersRoute: typeof AppOrganizationsSlugMembersRoute
  AppOrganizationsSlugRolesRoute: typeof AppOrganizationsSlugRolesRoute
  AppOrganizationsSlugSettingsRoute: typeof AppOrganizationsSlugSettingsRoute
  AppOrganizationsSlugProjectsProjectIdRoute: typeof AppOrganizationsSlugProjectsProjectIdRoute
  AppOrganizationsSlugProjectsIndexRoute: typeof AppOrganizationsSlugProjectsIndexRoute
}

const AppOrganizationsSlugRouteRouteChildren: AppOrganizationsSlugRouteRouteChildren =
  {
    AppOrganizationsSlugDashboardRoute: AppOrganizationsSlugDashboardRoute,
    AppOrganizationsSlugDetectionRoute: AppOrganizationsSlugDetectionRoute,
    AppOrganizationsSlugMembersRoute: AppOrganizationsSlugMembersRoute,
    AppOrganizationsSlugRolesRoute: AppOrganizationsSlugRolesRoute,
    AppOrganizationsSlugSettingsRoute: AppOrganizationsSlugSettingsRoute,
    AppOrganizationsSlugProjectsProjectIdRoute:
      AppOrganizationsSlugProjectsProjectIdRoute,
    AppOrganizationsSlugProjectsIndexRoute:
      AppOrganizationsSlugProjectsIndexRoute,
  }

const AppOrganizationsSlugRouteRouteWithChildren =
  AppOrganizationsSlugRouteRoute._addFileChildren(
    AppOrganizationsSlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrganizationsSlugRouteRoute: typeof AppOrganizationsSlugRouteRouteWithChildren
  AppOrganizationsNewRoute: typeof AppOrganizationsNewRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrganizationsSlugRouteRoute: AppOrganizationsSlugRouteRouteWithChildren,
  AppOrganizationsNewRoute: AppOrganizationsNewRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
